// // Mocks generated by Mockito 5.3.2 from annotations
// // in islamicapp/test/data/services/prayer_time_service_test.dart.
// // Do not manually edit this file.
//
// // ignore_for_file: no_leading_underscores_for_library_prefixes
// import 'dart:async' as _i4;
//
// import 'package:islamicapp/data/models/prayer_time_model/response_prayer_data_model.dart'
//     as _i2;
// import 'package:islamicapp/data/service/api_services/prayer_time_api_service/prayer_time_service.dart'
//     as _i3;
// import 'package:mockito/mockito.dart' as _i1;
//
// // ignore_for_file: type=lint
// // ignore_for_file: avoid_redundant_argument_values
// // ignore_for_file: avoid_setters_without_getters
// // ignore_for_file: comment_references
// // ignore_for_file: implementation_imports
// // ignore_for_file: invalid_use_of_visible_for_testing_member
// // ignore_for_file: prefer_const_constructors
// // ignore_for_file: unnecessary_parenthesis
// // ignore_for_file: camel_case_types
// // ignore_for_file: subtype_of_sealed_class
//
// class _FakeResponsePrayerModel_0 extends _i1.SmartFake
//     implements _i2.ResponsePrayerModel {
//   _FakeResponsePrayerModel_0(
//     Object parent,
//     Invocation parentInvocation,
//   ) : super(
//           parent,
//           parentInvocation,
//         );
// }
//
// /// A class which mocks [PrayerTimeService].
// ///
// /// See the documentation for Mockito's code generation for more information.
// class MockPrayerTimeService extends _i1.Mock implements _i3.PrayerTimeService {
//   MockPrayerTimeService() {
//     _i1.throwOnMissingStub(this);
//   }
//
//   @override
//   _i4.Future<_i2.ResponsePrayerModel> getPrayerTimes(
//     double? latitude,
//     double? longitude,
//     int? methodToCalculatePrayerTime,
//     String? date,
//   ) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #getPrayerTimes,
//           [
//             latitude,
//             longitude,
//             methodToCalculatePrayerTime,
//             date,
//           ],
//         ),
//         returnValue: _i4.Future<_i2.ResponsePrayerModel>.value(
//             _FakeResponsePrayerModel_0(
//           this,
//           Invocation.method(
//             #getPrayerTimes,
//             [
//               latitude,
//               longitude,
//               methodToCalculatePrayerTime,
//               date,
//             ],
//           ),
//         )),
//       ) as _i4.Future<_i2.ResponsePrayerModel>);
// }
